mkdir "EggAlbatross"
mkdir "EggHawk"
mkdir "EggEmperor"

mkdir "TeamBattleIcons\TeamSonic"
mkdir "TeamBattleIcons\TeamDark"
mkdir "TeamBattleIcons\TeamRose"
mkdir "TeamBattleIcons\TeamChaotix"
mkdir "EnemyIcons"
mkdir "CommonAssets"

mkdir "Klagen"
mkdir "E2000"
mkdir "EggMobile"
mkdir "Falco"
mkdir "EggMagician"
mkdir "MetalSonic1"
mkdir "MetalSonic2"
mkdir "EggPawn"
mkdir "EggPawnCasino"
mkdir "Rhinoliner"
mkdir "Flapper"
mkdir "Cameron"
mkdir "HeavyEggHammer"