
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox6;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Button Btn_OpenFile;

	private global::Gtk.Button Btn_SaveFile;

	private global::Gtk.ComboBox CmbBox_Item;

	private global::Gtk.Button btn_ClearAll;

	private global::Gtk.Button btn_RemoveObject;

	private global::Gtk.Button btn_CloneObject;

	private global::Gtk.Button btn_Tools;

	private global::Gtk.Button btn_Warp;

	private global::Gtk.HBox hbox6;

	private global::Gtk.Label lbl_SonicX;

	private global::Gtk.Label lbl_SonicY;

	private global::Gtk.Label lbl_SonicZ;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Label lbl_ObjectNameLabel;

	private global::Gtk.Label lbl_ObjectListLabel;

	private global::Gtk.Label lbl_ObjectNumberLabel;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Label lbl_SelectByNameLabel;

	private global::Gtk.ComboBox CmbBox_SelectByName;

	private global::Gtk.Label lbl_SelectByTypeLabel;

	private global::Gtk.ComboBox CmbBox_SelectByType;

	private global::Gtk.Label lbl_SelectByIDLabel;

	private global::Gtk.ComboBox CmbBox_SelectByID;

	private global::Gtk.Label lbl_Separator;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label lbl_PositionX;

	private global::Gtk.SpinButton SpinBtn_PositionX;

	private global::Gtk.Label lbl_PositionY;

	private global::Gtk.SpinButton SpinBtn_PositionY;

	private global::Gtk.Label lbl_PositionZ;

	private global::Gtk.SpinButton SpinBtn_PositionZ;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Label lbl_RotationX;

	private global::Gtk.SpinButton SpinBtn_RotationX;

	private global::Gtk.Label lbl_RotationY;

	private global::Gtk.SpinButton SpinBtn_RotationY;

	private global::Gtk.Label lbl_RotationZ;

	private global::Gtk.SpinButton SpinBtn_RotationZ;

	private global::Gtk.HBox hbox10;

	private global::Gtk.Label lbl_ObjectList;

	private global::Gtk.SpinButton SpinBtn_ObjectList;

	private global::Gtk.Label lbl_ObjectID;

	private global::Gtk.SpinButton SpinBtn_ObjectID;

	private global::Gtk.Label lbl_LinkingID;

	private global::Gtk.SpinButton SpinBtn_LinkingID;

	private global::Gtk.Label lbl_LoadDistanceMultiplier;

	private global::Gtk.SpinButton SpinBtn_LoadDistanceMultiplier;

	private global::Gtk.Label lbl_PropertyID;

	private global::Gtk.SpinButton SpinBtn_PropertyID;

	private global::Gtk.Label lbl_Separator2;

	private global::Gtk.HBox hbox15;

	private global::Gtk.Label lbl_IgnoredValue1;

	private global::Gtk.Label lbl_ObejctTeam1;

	private global::Gtk.Label lbl_MysteryByte1;

	private global::Gtk.Label lbl_MysteryFourBytes;

	private global::Gtk.HBox hbox17;

	private global::Gtk.SpinButton SpinBtn_IgnoredValue1;

	private global::Gtk.ComboBox CmbBox_ObjectTeam1;

	private global::Gtk.SpinButton SpinBtn_MysteryByte;

	private global::Gtk.SpinButton SpinBtn_MysteryFourBytes1;

	private global::Gtk.HBox hbox16;

	private global::Gtk.Label lbl_IgnoredValue2;

	private global::Gtk.Label lbl_ObejctTeam2;

	private global::Gtk.Label lbl_MysteryByte2;

	private global::Gtk.Label lbl_MysteryFourBytes2;

	private global::Gtk.HBox hbox2;

	private global::Gtk.SpinButton SpinBtn_IgnoredValue2;

	private global::Gtk.ComboBox CmbBox_ObjectTeam2;

	private global::Gtk.SpinButton SpinBtn_MysteryByte2;

	private global::Gtk.SpinButton SpinBtn_MysteryFourBytes2;

	private global::Gtk.Label lbl_Separator3;

	private global::Gtk.HBox hbox8;

	private global::Gtk.ComboBox CmbBox_Property;

	private global::Gtk.Label lbl_MiscActivator;

	private global::Gtk.SpinButton SpinBtn_MiscActivator;

	private global::Gtk.Label lbl_MiscEntryID;

	private global::Gtk.SpinButton SpinBtn_MiscEntryID;

	private global::Gtk.Notebook notebook1;

	private global::Gtk.VBox vbox3;

	private global::Gtk.HBox hbox21;

	private global::Gtk.Label lbl_ObjectProperty1;

	private global::Gtk.Label lbl_ObjectProperty2;

	private global::Gtk.Label lbl_ObjectProperty3;

	private global::Gtk.Label lbl_ObjectProperty4;

	private global::Gtk.HBox hbox22;

	private global::Gtk.SpinButton SpinBtn_ObjectProperty1;

	private global::Gtk.SpinButton SpinBtn_ObjectProperty2;

	private global::Gtk.SpinButton SpinBtn_ObjectProperty3;

	private global::Gtk.SpinButton SpinBtn_ObjectProperty4;

	private global::Gtk.HBox hbox14;

	private global::Gtk.Label lbl_ObjectProperty5;

	private global::Gtk.Label lbl_ObjectProperty6;

	private global::Gtk.Label lbl_ObjectProperty7;

	private global::Gtk.Label lbl_ObjectProperty8;

	private global::Gtk.HBox hbox18;

	private global::Gtk.SpinButton SpinBtn_ObjectProperty5;

	private global::Gtk.SpinButton SpinBtn_ObjectProperty6;

	private global::Gtk.SpinButton SpinBtn_ObjectProperty7;

	private global::Gtk.SpinButton SpinBtn_ObjectProperty8;

	private global::Gtk.HBox hbox20;

	private global::Gtk.Button Btn_ViewAsFloats;

	private global::Gtk.Button Btn_ViewAsIntegers;

	private global::Gtk.Label Page_Floats;

	private global::Gtk.VBox vbox2;

	private global::Gtk.HBox hbox19;

	private global::Gtk.Label Page_Bytes;

	private global::Gtk.HBox hbox23;

	private global::Gtk.Label lbl_Statusbar1;

	private global::Gtk.Label lbl_Statusbar2;

	private global::Gtk.Label lbl_Statusbar3;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.WidthRequest = 300;
		this.CanFocus = true;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Heroes Layout Editor");
		this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Modal = true;
		this.BorderWidth = ((uint)(15));
		this.AllowShrink = true;
		this.DefaultHeight = 780;
		this.Gravity = ((global::Gdk.Gravity)(2));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox6 = new global::Gtk.VBox();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		this.hbox4.BorderWidth = ((uint)(5));
		// Container child hbox4.Gtk.Box+BoxChild
		this.Btn_OpenFile = new global::Gtk.Button();
		this.Btn_OpenFile.CanFocus = true;
		this.Btn_OpenFile.Name = "Btn_OpenFile";
		this.Btn_OpenFile.UseUnderline = true;
		global::Gtk.Image w1 = new global::Gtk.Image();
		w1.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-open", global::Gtk.IconSize.Menu);
		this.Btn_OpenFile.Image = w1;
		this.hbox4.Add(this.Btn_OpenFile);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.Btn_OpenFile]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.Btn_SaveFile = new global::Gtk.Button();
		this.Btn_SaveFile.CanFocus = true;
		this.Btn_SaveFile.Name = "Btn_SaveFile";
		this.Btn_SaveFile.UseUnderline = true;
		global::Gtk.Image w3 = new global::Gtk.Image();
		w3.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-save", global::Gtk.IconSize.Menu);
		this.Btn_SaveFile.Image = w3;
		this.hbox4.Add(this.Btn_SaveFile);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.Btn_SaveFile]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.CmbBox_Item = global::Gtk.ComboBox.NewText();
		this.CmbBox_Item.AppendText(global::Mono.Unix.Catalog.GetString("(1337.32, 4200.91, 45269.92) Sample Object <00>"));
		this.CmbBox_Item.Events = ((global::Gdk.EventMask)(2097152));
		this.CmbBox_Item.Name = "CmbBox_Item";
		this.CmbBox_Item.Active = 0;
		this.hbox4.Add(this.CmbBox_Item);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.CmbBox_Item]));
		w5.Position = 2;
		w5.Padding = ((uint)(20));
		// Container child hbox4.Gtk.Box+BoxChild
		this.btn_ClearAll = new global::Gtk.Button();
		this.btn_ClearAll.CanFocus = true;
		this.btn_ClearAll.Name = "btn_ClearAll";
		this.btn_ClearAll.UseUnderline = true;
		this.btn_ClearAll.Label = global::Mono.Unix.Catalog.GetString("Clear All");
		global::Gtk.Image w6 = new global::Gtk.Image();
		w6.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-clear", global::Gtk.IconSize.LargeToolbar);
		this.btn_ClearAll.Image = w6;
		this.hbox4.Add(this.btn_ClearAll);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.btn_ClearAll]));
		w7.Position = 3;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btn_RemoveObject = new global::Gtk.Button();
		this.btn_RemoveObject.CanFocus = true;
		this.btn_RemoveObject.Name = "btn_RemoveObject";
		this.btn_RemoveObject.UseUnderline = true;
		this.btn_RemoveObject.Label = global::Mono.Unix.Catalog.GetString("Clear");
		global::Gtk.Image w8 = new global::Gtk.Image();
		w8.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-delete", global::Gtk.IconSize.Menu);
		this.btn_RemoveObject.Image = w8;
		this.hbox4.Add(this.btn_RemoveObject);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.btn_RemoveObject]));
		w9.Position = 4;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btn_CloneObject = new global::Gtk.Button();
		this.btn_CloneObject.CanFocus = true;
		this.btn_CloneObject.Name = "btn_CloneObject";
		this.btn_CloneObject.UseUnderline = true;
		this.btn_CloneObject.Label = global::Mono.Unix.Catalog.GetString("Clone");
		global::Gtk.Image w10 = new global::Gtk.Image();
		w10.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-copy", global::Gtk.IconSize.LargeToolbar);
		this.btn_CloneObject.Image = w10;
		this.hbox4.Add(this.btn_CloneObject);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.btn_CloneObject]));
		w11.Position = 5;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btn_Tools = new global::Gtk.Button();
		this.btn_Tools.CanFocus = true;
		this.btn_Tools.Name = "btn_Tools";
		this.btn_Tools.UseUnderline = true;
		this.btn_Tools.Label = global::Mono.Unix.Catalog.GetString("Tools");
		global::Gtk.Image w12 = new global::Gtk.Image();
		w12.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-execute", global::Gtk.IconSize.Menu);
		this.btn_Tools.Image = w12;
		this.hbox4.Add(this.btn_Tools);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.btn_Tools]));
		w13.Position = 6;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btn_Warp = new global::Gtk.Button();
		this.btn_Warp.CanFocus = true;
		this.btn_Warp.Name = "btn_Warp";
		this.btn_Warp.UseUnderline = true;
		this.btn_Warp.Label = global::Mono.Unix.Catalog.GetString("Warp");
		global::Gtk.Image w14 = new global::Gtk.Image();
		w14.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-go-forward", global::Gtk.IconSize.Menu);
		this.btn_Warp.Image = w14;
		this.hbox4.Add(this.btn_Warp);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.btn_Warp]));
		w15.Position = 7;
		w15.Expand = false;
		w15.Fill = false;
		this.vbox6.Add(this.hbox4);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox4]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Homogeneous = true;
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.lbl_SonicX = new global::Gtk.Label();
		this.lbl_SonicX.Name = "lbl_SonicX";
		this.lbl_SonicX.Ypad = 5;
		this.lbl_SonicX.LabelProp = global::Mono.Unix.Catalog.GetString("Sonic X: N/A");
		this.hbox6.Add(this.lbl_SonicX);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.lbl_SonicX]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.lbl_SonicY = new global::Gtk.Label();
		this.lbl_SonicY.Name = "lbl_SonicY";
		this.lbl_SonicY.Ypad = 5;
		this.lbl_SonicY.LabelProp = global::Mono.Unix.Catalog.GetString("Sonic Y: N/A");
		this.hbox6.Add(this.lbl_SonicY);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.lbl_SonicY]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.lbl_SonicZ = new global::Gtk.Label();
		this.lbl_SonicZ.Name = "lbl_SonicZ";
		this.lbl_SonicZ.Ypad = 5;
		this.lbl_SonicZ.LabelProp = global::Mono.Unix.Catalog.GetString("Sonic Z: N/A");
		this.hbox6.Add(this.lbl_SonicZ);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.lbl_SonicZ]));
		w19.Position = 2;
		w19.Expand = false;
		w19.Fill = false;
		this.vbox6.Add(this.hbox6);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox6]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Homogeneous = true;
		// Container child hbox3.Gtk.Box+BoxChild
		this.lbl_ObjectNameLabel = new global::Gtk.Label();
		this.lbl_ObjectNameLabel.Name = "lbl_ObjectNameLabel";
		this.lbl_ObjectNameLabel.Ypad = 5;
		this.lbl_ObjectNameLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Object Name: Spring");
		this.hbox3.Add(this.lbl_ObjectNameLabel);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.lbl_ObjectNameLabel]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.lbl_ObjectListLabel = new global::Gtk.Label();
		this.lbl_ObjectListLabel.Name = "lbl_ObjectListLabel";
		this.lbl_ObjectListLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Object List: Common Objects");
		this.hbox3.Add(this.lbl_ObjectListLabel);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.lbl_ObjectListLabel]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.lbl_ObjectNumberLabel = new global::Gtk.Label();
		this.lbl_ObjectNumberLabel.Name = "lbl_ObjectNumberLabel";
		this.lbl_ObjectNumberLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Object Number: 0000 / 2047");
		this.hbox3.Add(this.lbl_ObjectNumberLabel);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.lbl_ObjectNumberLabel]));
		w23.Position = 2;
		w23.Expand = false;
		w23.Fill = false;
		this.vbox6.Add(this.hbox3);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox3]));
		w24.Position = 2;
		w24.Expand = false;
		w24.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Homogeneous = true;
		// Container child hbox5.Gtk.Box+BoxChild
		this.lbl_SelectByNameLabel = new global::Gtk.Label();
		this.lbl_SelectByNameLabel.Name = "lbl_SelectByNameLabel";
		this.lbl_SelectByNameLabel.Ypad = 10;
		this.lbl_SelectByNameLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Select By Name:");
		this.hbox5.Add(this.lbl_SelectByNameLabel);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.lbl_SelectByNameLabel]));
		w25.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.CmbBox_SelectByName = global::Gtk.ComboBox.NewText();
		this.CmbBox_SelectByName.Name = "CmbBox_SelectByName";
		this.hbox5.Add(this.CmbBox_SelectByName);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.CmbBox_SelectByName]));
		w26.Position = 1;
		// Container child hbox5.Gtk.Box+BoxChild
		this.lbl_SelectByTypeLabel = new global::Gtk.Label();
		this.lbl_SelectByTypeLabel.Name = "lbl_SelectByTypeLabel";
		this.lbl_SelectByTypeLabel.Ypad = 10;
		this.lbl_SelectByTypeLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Select By List:");
		this.hbox5.Add(this.lbl_SelectByTypeLabel);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.lbl_SelectByTypeLabel]));
		w27.Position = 2;
		// Container child hbox5.Gtk.Box+BoxChild
		this.CmbBox_SelectByType = global::Gtk.ComboBox.NewText();
		this.CmbBox_SelectByType.Name = "CmbBox_SelectByType";
		this.hbox5.Add(this.CmbBox_SelectByType);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.CmbBox_SelectByType]));
		w28.Position = 3;
		// Container child hbox5.Gtk.Box+BoxChild
		this.lbl_SelectByIDLabel = new global::Gtk.Label();
		this.lbl_SelectByIDLabel.Name = "lbl_SelectByIDLabel";
		this.lbl_SelectByIDLabel.Ypad = 10;
		this.lbl_SelectByIDLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Select List Object:");
		this.hbox5.Add(this.lbl_SelectByIDLabel);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.lbl_SelectByIDLabel]));
		w29.Position = 4;
		// Container child hbox5.Gtk.Box+BoxChild
		this.CmbBox_SelectByID = global::Gtk.ComboBox.NewText();
		this.CmbBox_SelectByID.Name = "CmbBox_SelectByID";
		this.hbox5.Add(this.CmbBox_SelectByID);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.CmbBox_SelectByID]));
		w30.Position = 5;
		this.vbox6.Add(this.hbox5);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox5]));
		w31.Position = 3;
		w31.Expand = false;
		w31.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.lbl_Separator = new global::Gtk.Label();
		this.lbl_Separator.Name = "lbl_Separator";
		this.lbl_Separator.LabelProp = global::Mono.Unix.Catalog.GetString("-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
		this.vbox6.Add(this.lbl_Separator);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.lbl_Separator]));
		w32.Position = 4;
		w32.Expand = false;
		w32.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Homogeneous = true;
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.lbl_PositionX = new global::Gtk.Label();
		this.lbl_PositionX.Name = "lbl_PositionX";
		this.lbl_PositionX.Ypad = 5;
		this.lbl_PositionX.LabelProp = global::Mono.Unix.Catalog.GetString("Position X");
		this.lbl_PositionX.UseUnderline = true;
		this.hbox1.Add(this.lbl_PositionX);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.lbl_PositionX]));
		w33.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.SpinBtn_PositionX = new global::Gtk.SpinButton(-1.175494E+38, 3.402823E+38, 1);
		this.SpinBtn_PositionX.WidthRequest = 200;
		this.SpinBtn_PositionX.CanFocus = true;
		this.SpinBtn_PositionX.Name = "SpinBtn_PositionX";
		this.SpinBtn_PositionX.Adjustment.PageIncrement = 10;
		this.SpinBtn_PositionX.ClimbRate = 1;
		this.SpinBtn_PositionX.Digits = ((uint)(7));
		this.SpinBtn_PositionX.Numeric = true;
		this.SpinBtn_PositionX.Value = 1230;
		this.hbox1.Add(this.SpinBtn_PositionX);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.SpinBtn_PositionX]));
		w34.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.lbl_PositionY = new global::Gtk.Label();
		this.lbl_PositionY.Name = "lbl_PositionY";
		this.lbl_PositionY.Ypad = 5;
		this.lbl_PositionY.LabelProp = global::Mono.Unix.Catalog.GetString("Position Y");
		this.hbox1.Add(this.lbl_PositionY);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.lbl_PositionY]));
		w35.Position = 2;
		w35.Expand = false;
		w35.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.SpinBtn_PositionY = new global::Gtk.SpinButton(-1.175494E+38, 3.402823E+38, 1);
		this.SpinBtn_PositionY.WidthRequest = 200;
		this.SpinBtn_PositionY.CanFocus = true;
		this.SpinBtn_PositionY.Name = "SpinBtn_PositionY";
		this.SpinBtn_PositionY.Adjustment.PageIncrement = 10;
		this.SpinBtn_PositionY.ClimbRate = 1;
		this.SpinBtn_PositionY.Digits = ((uint)(7));
		this.SpinBtn_PositionY.Numeric = true;
		this.SpinBtn_PositionY.Value = 1234;
		this.hbox1.Add(this.SpinBtn_PositionY);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.SpinBtn_PositionY]));
		w36.Position = 3;
		// Container child hbox1.Gtk.Box+BoxChild
		this.lbl_PositionZ = new global::Gtk.Label();
		this.lbl_PositionZ.Name = "lbl_PositionZ";
		this.lbl_PositionZ.Ypad = 5;
		this.lbl_PositionZ.LabelProp = global::Mono.Unix.Catalog.GetString("Position Z");
		this.hbox1.Add(this.lbl_PositionZ);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.lbl_PositionZ]));
		w37.Position = 4;
		w37.Expand = false;
		w37.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.SpinBtn_PositionZ = new global::Gtk.SpinButton(-1.175494E+38, 3.402823E+38, 1);
		this.SpinBtn_PositionZ.WidthRequest = 200;
		this.SpinBtn_PositionZ.CanFocus = true;
		this.SpinBtn_PositionZ.Name = "SpinBtn_PositionZ";
		this.SpinBtn_PositionZ.Adjustment.PageIncrement = 10;
		this.SpinBtn_PositionZ.ClimbRate = 1;
		this.SpinBtn_PositionZ.Digits = ((uint)(7));
		this.SpinBtn_PositionZ.Numeric = true;
		this.SpinBtn_PositionZ.Value = 1234;
		this.hbox1.Add(this.SpinBtn_PositionZ);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.SpinBtn_PositionZ]));
		w38.Position = 5;
		this.vbox6.Add(this.hbox1);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox1]));
		w39.Position = 5;
		w39.Expand = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.HeightRequest = 58;
		this.hbox7.Name = "hbox7";
		this.hbox7.Homogeneous = true;
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.lbl_RotationX = new global::Gtk.Label();
		this.lbl_RotationX.Name = "lbl_RotationX";
		this.lbl_RotationX.Ypad = 5;
		this.lbl_RotationX.LabelProp = global::Mono.Unix.Catalog.GetString("Rotation X");
		this.hbox7.Add(this.lbl_RotationX);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.lbl_RotationX]));
		w40.Position = 0;
		w40.Expand = false;
		w40.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.SpinBtn_RotationX = new global::Gtk.SpinButton(-1.175494E+38, 3.402823E+38, 1);
		this.SpinBtn_RotationX.WidthRequest = 200;
		this.SpinBtn_RotationX.CanFocus = true;
		this.SpinBtn_RotationX.Name = "SpinBtn_RotationX";
		this.SpinBtn_RotationX.Adjustment.PageIncrement = 10;
		this.SpinBtn_RotationX.ClimbRate = 1;
		this.SpinBtn_RotationX.Digits = ((uint)(7));
		this.SpinBtn_RotationX.Numeric = true;
		this.SpinBtn_RotationX.Value = 94;
		this.hbox7.Add(this.SpinBtn_RotationX);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.SpinBtn_RotationX]));
		w41.Position = 1;
		// Container child hbox7.Gtk.Box+BoxChild
		this.lbl_RotationY = new global::Gtk.Label();
		this.lbl_RotationY.Name = "lbl_RotationY";
		this.lbl_RotationY.Ypad = 5;
		this.lbl_RotationY.LabelProp = global::Mono.Unix.Catalog.GetString("Rotation Y");
		this.hbox7.Add(this.lbl_RotationY);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.lbl_RotationY]));
		w42.Position = 2;
		w42.Expand = false;
		w42.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.SpinBtn_RotationY = new global::Gtk.SpinButton(-1.175494E+38, 3.402823E+38, 1);
		this.SpinBtn_RotationY.WidthRequest = 200;
		this.SpinBtn_RotationY.CanFocus = true;
		this.SpinBtn_RotationY.Name = "SpinBtn_RotationY";
		this.SpinBtn_RotationY.Adjustment.PageIncrement = 10;
		this.SpinBtn_RotationY.ClimbRate = 1;
		this.SpinBtn_RotationY.Digits = ((uint)(7));
		this.SpinBtn_RotationY.Numeric = true;
		this.SpinBtn_RotationY.Value = 176;
		this.hbox7.Add(this.SpinBtn_RotationY);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.SpinBtn_RotationY]));
		w43.Position = 3;
		// Container child hbox7.Gtk.Box+BoxChild
		this.lbl_RotationZ = new global::Gtk.Label();
		this.lbl_RotationZ.Name = "lbl_RotationZ";
		this.lbl_RotationZ.Ypad = 5;
		this.lbl_RotationZ.LabelProp = global::Mono.Unix.Catalog.GetString("Rotation Z");
		this.hbox7.Add(this.lbl_RotationZ);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.lbl_RotationZ]));
		w44.Position = 4;
		w44.Expand = false;
		w44.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.SpinBtn_RotationZ = new global::Gtk.SpinButton(-1.175494E+38, 3.402823E+38, 1);
		this.SpinBtn_RotationZ.WidthRequest = 200;
		this.SpinBtn_RotationZ.CanFocus = true;
		this.SpinBtn_RotationZ.Name = "SpinBtn_RotationZ";
		this.SpinBtn_RotationZ.Adjustment.PageIncrement = 10;
		this.SpinBtn_RotationZ.ClimbRate = 1;
		this.SpinBtn_RotationZ.Digits = ((uint)(7));
		this.SpinBtn_RotationZ.Numeric = true;
		this.SpinBtn_RotationZ.Value = 270;
		this.hbox7.Add(this.SpinBtn_RotationZ);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.SpinBtn_RotationZ]));
		w45.Position = 5;
		this.vbox6.Add(this.hbox7);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox7]));
		w46.Position = 6;
		w46.Expand = false;
		w46.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox();
		this.hbox10.Name = "hbox10";
		this.hbox10.Homogeneous = true;
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.lbl_ObjectList = new global::Gtk.Label();
		this.lbl_ObjectList.Name = "lbl_ObjectList";
		this.lbl_ObjectList.Ypad = 5;
		this.lbl_ObjectList.LabelProp = global::Mono.Unix.Catalog.GetString("Object List");
		this.hbox10.Add(this.lbl_ObjectList);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.lbl_ObjectList]));
		w47.Position = 0;
		// Container child hbox10.Gtk.Box+BoxChild
		this.SpinBtn_ObjectList = new global::Gtk.SpinButton(0, 255, 1);
		this.SpinBtn_ObjectList.WidthRequest = 0;
		this.SpinBtn_ObjectList.CanFocus = true;
		this.SpinBtn_ObjectList.Name = "SpinBtn_ObjectList";
		this.SpinBtn_ObjectList.Adjustment.PageIncrement = 1;
		this.SpinBtn_ObjectList.ClimbRate = 1;
		this.SpinBtn_ObjectList.Numeric = true;
		this.hbox10.Add(this.SpinBtn_ObjectList);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.SpinBtn_ObjectList]));
		w48.Position = 1;
		// Container child hbox10.Gtk.Box+BoxChild
		this.lbl_ObjectID = new global::Gtk.Label();
		this.lbl_ObjectID.Name = "lbl_ObjectID";
		this.lbl_ObjectID.Ypad = 5;
		this.lbl_ObjectID.LabelProp = global::Mono.Unix.Catalog.GetString("Object ID");
		this.hbox10.Add(this.lbl_ObjectID);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.lbl_ObjectID]));
		w49.Position = 2;
		w49.Expand = false;
		w49.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.SpinBtn_ObjectID = new global::Gtk.SpinButton(0, 255, 1);
		this.SpinBtn_ObjectID.WidthRequest = 0;
		this.SpinBtn_ObjectID.CanFocus = true;
		this.SpinBtn_ObjectID.Name = "SpinBtn_ObjectID";
		this.SpinBtn_ObjectID.Adjustment.PageIncrement = 1;
		this.SpinBtn_ObjectID.ClimbRate = 1;
		this.SpinBtn_ObjectID.Numeric = true;
		this.hbox10.Add(this.SpinBtn_ObjectID);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.SpinBtn_ObjectID]));
		w50.Position = 3;
		// Container child hbox10.Gtk.Box+BoxChild
		this.lbl_LinkingID = new global::Gtk.Label();
		this.lbl_LinkingID.Name = "lbl_LinkingID";
		this.lbl_LinkingID.Ypad = 5;
		this.lbl_LinkingID.LabelProp = global::Mono.Unix.Catalog.GetString("Linking ID");
		this.hbox10.Add(this.lbl_LinkingID);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.lbl_LinkingID]));
		w51.Position = 4;
		w51.Expand = false;
		w51.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.SpinBtn_LinkingID = new global::Gtk.SpinButton(0, 255, 1);
		this.SpinBtn_LinkingID.WidthRequest = 0;
		this.SpinBtn_LinkingID.CanFocus = true;
		this.SpinBtn_LinkingID.Name = "SpinBtn_LinkingID";
		this.SpinBtn_LinkingID.Adjustment.PageIncrement = 1;
		this.SpinBtn_LinkingID.ClimbRate = 1;
		this.SpinBtn_LinkingID.Numeric = true;
		this.hbox10.Add(this.SpinBtn_LinkingID);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.SpinBtn_LinkingID]));
		w52.Position = 5;
		// Container child hbox10.Gtk.Box+BoxChild
		this.lbl_LoadDistanceMultiplier = new global::Gtk.Label();
		this.lbl_LoadDistanceMultiplier.Name = "lbl_LoadDistanceMultiplier";
		this.lbl_LoadDistanceMultiplier.Ypad = 5;
		this.lbl_LoadDistanceMultiplier.LabelProp = global::Mono.Unix.Catalog.GetString("Load Dist");
		this.hbox10.Add(this.lbl_LoadDistanceMultiplier);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.lbl_LoadDistanceMultiplier]));
		w53.Position = 6;
		w53.Expand = false;
		w53.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.SpinBtn_LoadDistanceMultiplier = new global::Gtk.SpinButton(0, 255, 1);
		this.SpinBtn_LoadDistanceMultiplier.WidthRequest = 0;
		this.SpinBtn_LoadDistanceMultiplier.CanFocus = true;
		this.SpinBtn_LoadDistanceMultiplier.Name = "SpinBtn_LoadDistanceMultiplier";
		this.SpinBtn_LoadDistanceMultiplier.Adjustment.PageIncrement = 1;
		this.SpinBtn_LoadDistanceMultiplier.ClimbRate = 1;
		this.SpinBtn_LoadDistanceMultiplier.Numeric = true;
		this.hbox10.Add(this.SpinBtn_LoadDistanceMultiplier);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.SpinBtn_LoadDistanceMultiplier]));
		w54.Position = 7;
		// Container child hbox10.Gtk.Box+BoxChild
		this.lbl_PropertyID = new global::Gtk.Label();
		this.lbl_PropertyID.Name = "lbl_PropertyID";
		this.lbl_PropertyID.Ypad = 5;
		this.lbl_PropertyID.LabelProp = global::Mono.Unix.Catalog.GetString("Property ID");
		this.hbox10.Add(this.lbl_PropertyID);
		global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.lbl_PropertyID]));
		w55.Position = 8;
		w55.Expand = false;
		w55.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.SpinBtn_PropertyID = new global::Gtk.SpinButton(0, 65535, 1);
		this.SpinBtn_PropertyID.WidthRequest = 0;
		this.SpinBtn_PropertyID.CanFocus = true;
		this.SpinBtn_PropertyID.Name = "SpinBtn_PropertyID";
		this.SpinBtn_PropertyID.Adjustment.PageIncrement = 1;
		this.SpinBtn_PropertyID.ClimbRate = 1;
		this.SpinBtn_PropertyID.Numeric = true;
		this.hbox10.Add(this.SpinBtn_PropertyID);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.SpinBtn_PropertyID]));
		w56.Position = 9;
		this.vbox6.Add(this.hbox10);
		global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox10]));
		w57.Position = 7;
		w57.Expand = false;
		w57.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.lbl_Separator2 = new global::Gtk.Label();
		this.lbl_Separator2.Name = "lbl_Separator2";
		this.lbl_Separator2.LabelProp = global::Mono.Unix.Catalog.GetString("-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
		this.vbox6.Add(this.lbl_Separator2);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.lbl_Separator2]));
		w58.Position = 8;
		w58.Expand = false;
		w58.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox15 = new global::Gtk.HBox();
		this.hbox15.Name = "hbox15";
		this.hbox15.Homogeneous = true;
		this.hbox15.Spacing = 6;
		// Container child hbox15.Gtk.Box+BoxChild
		this.lbl_IgnoredValue1 = new global::Gtk.Label();
		this.lbl_IgnoredValue1.Name = "lbl_IgnoredValue1";
		this.lbl_IgnoredValue1.Ypad = 5;
		this.lbl_IgnoredValue1.LabelProp = global::Mono.Unix.Catalog.GetString("Ignored Value #1");
		this.lbl_IgnoredValue1.UseUnderline = true;
		this.hbox15.Add(this.lbl_IgnoredValue1);
		global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.lbl_IgnoredValue1]));
		w59.Position = 0;
		w59.Expand = false;
		w59.Fill = false;
		// Container child hbox15.Gtk.Box+BoxChild
		this.lbl_ObejctTeam1 = new global::Gtk.Label();
		this.lbl_ObejctTeam1.Name = "lbl_ObejctTeam1";
		this.lbl_ObejctTeam1.Ypad = 5;
		this.lbl_ObejctTeam1.LabelProp = global::Mono.Unix.Catalog.GetString("Object Team #1");
		this.lbl_ObejctTeam1.UseUnderline = true;
		this.hbox15.Add(this.lbl_ObejctTeam1);
		global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.lbl_ObejctTeam1]));
		w60.Position = 1;
		w60.Expand = false;
		w60.Fill = false;
		// Container child hbox15.Gtk.Box+BoxChild
		this.lbl_MysteryByte1 = new global::Gtk.Label();
		this.lbl_MysteryByte1.Name = "lbl_MysteryByte1";
		this.lbl_MysteryByte1.Ypad = 5;
		this.lbl_MysteryByte1.LabelProp = global::Mono.Unix.Catalog.GetString("Mystery Byte #1");
		this.lbl_MysteryByte1.UseUnderline = true;
		this.hbox15.Add(this.lbl_MysteryByte1);
		global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.lbl_MysteryByte1]));
		w61.Position = 2;
		w61.Expand = false;
		w61.Fill = false;
		// Container child hbox15.Gtk.Box+BoxChild
		this.lbl_MysteryFourBytes = new global::Gtk.Label();
		this.lbl_MysteryFourBytes.Name = "lbl_MysteryFourBytes";
		this.lbl_MysteryFourBytes.Ypad = 5;
		this.lbl_MysteryFourBytes.LabelProp = global::Mono.Unix.Catalog.GetString("Mystery Four Bytes #1");
		this.lbl_MysteryFourBytes.UseUnderline = true;
		this.hbox15.Add(this.lbl_MysteryFourBytes);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.lbl_MysteryFourBytes]));
		w62.Position = 3;
		w62.Expand = false;
		w62.Fill = false;
		this.vbox6.Add(this.hbox15);
		global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox15]));
		w63.Position = 9;
		w63.Expand = false;
		w63.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox17 = new global::Gtk.HBox();
		this.hbox17.Name = "hbox17";
		this.hbox17.Homogeneous = true;
		this.hbox17.Spacing = 6;
		// Container child hbox17.Gtk.Box+BoxChild
		this.SpinBtn_IgnoredValue1 = new global::Gtk.SpinButton(0, 65535, 1);
		this.SpinBtn_IgnoredValue1.WidthRequest = 200;
		this.SpinBtn_IgnoredValue1.CanFocus = true;
		this.SpinBtn_IgnoredValue1.Name = "SpinBtn_IgnoredValue1";
		this.SpinBtn_IgnoredValue1.Adjustment.PageIncrement = 1;
		this.SpinBtn_IgnoredValue1.ClimbRate = 1;
		this.SpinBtn_IgnoredValue1.Numeric = true;
		this.SpinBtn_IgnoredValue1.Value = 1;
		this.hbox17.Add(this.SpinBtn_IgnoredValue1);
		global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.SpinBtn_IgnoredValue1]));
		w64.Position = 0;
		w64.Expand = false;
		w64.Fill = false;
		// Container child hbox17.Gtk.Box+BoxChild
		this.CmbBox_ObjectTeam1 = global::Gtk.ComboBox.NewText();
		this.CmbBox_ObjectTeam1.AppendText(global::Mono.Unix.Catalog.GetString("Base/All"));
		this.CmbBox_ObjectTeam1.AppendText(global::Mono.Unix.Catalog.GetString("Sonic"));
		this.CmbBox_ObjectTeam1.AppendText(global::Mono.Unix.Catalog.GetString("Dark"));
		this.CmbBox_ObjectTeam1.AppendText(global::Mono.Unix.Catalog.GetString("Rose"));
		this.CmbBox_ObjectTeam1.AppendText(global::Mono.Unix.Catalog.GetString("Chaotix"));
		this.CmbBox_ObjectTeam1.AppendText(global::Mono.Unix.Catalog.GetString("Super Hard"));
		this.CmbBox_ObjectTeam1.WidthRequest = 200;
		this.CmbBox_ObjectTeam1.Name = "CmbBox_ObjectTeam1";
		this.CmbBox_ObjectTeam1.Active = 0;
		this.hbox17.Add(this.CmbBox_ObjectTeam1);
		global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.CmbBox_ObjectTeam1]));
		w65.Position = 1;
		w65.Expand = false;
		w65.Fill = false;
		// Container child hbox17.Gtk.Box+BoxChild
		this.SpinBtn_MysteryByte = new global::Gtk.SpinButton(0, 255, 1);
		this.SpinBtn_MysteryByte.WidthRequest = 200;
		this.SpinBtn_MysteryByte.CanFocus = true;
		this.SpinBtn_MysteryByte.Name = "SpinBtn_MysteryByte";
		this.SpinBtn_MysteryByte.Adjustment.PageIncrement = 1;
		this.SpinBtn_MysteryByte.ClimbRate = 1;
		this.SpinBtn_MysteryByte.Numeric = true;
		this.hbox17.Add(this.SpinBtn_MysteryByte);
		global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.SpinBtn_MysteryByte]));
		w66.Position = 2;
		w66.Expand = false;
		w66.Fill = false;
		// Container child hbox17.Gtk.Box+BoxChild
		this.SpinBtn_MysteryFourBytes1 = new global::Gtk.SpinButton(0, 4294967295, 1);
		this.SpinBtn_MysteryFourBytes1.WidthRequest = 200;
		this.SpinBtn_MysteryFourBytes1.CanFocus = true;
		this.SpinBtn_MysteryFourBytes1.Name = "SpinBtn_MysteryFourBytes1";
		this.SpinBtn_MysteryFourBytes1.Adjustment.PageIncrement = 1;
		this.SpinBtn_MysteryFourBytes1.ClimbRate = 1;
		this.SpinBtn_MysteryFourBytes1.Numeric = true;
		this.hbox17.Add(this.SpinBtn_MysteryFourBytes1);
		global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.SpinBtn_MysteryFourBytes1]));
		w67.Position = 3;
		w67.Expand = false;
		w67.Fill = false;
		this.vbox6.Add(this.hbox17);
		global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox17]));
		w68.Position = 10;
		w68.Expand = false;
		w68.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox16 = new global::Gtk.HBox();
		this.hbox16.Name = "hbox16";
		this.hbox16.Homogeneous = true;
		this.hbox16.Spacing = 6;
		// Container child hbox16.Gtk.Box+BoxChild
		this.lbl_IgnoredValue2 = new global::Gtk.Label();
		this.lbl_IgnoredValue2.Name = "lbl_IgnoredValue2";
		this.lbl_IgnoredValue2.Ypad = 5;
		this.lbl_IgnoredValue2.LabelProp = global::Mono.Unix.Catalog.GetString("Ignored Value #2");
		this.lbl_IgnoredValue2.UseUnderline = true;
		this.hbox16.Add(this.lbl_IgnoredValue2);
		global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.lbl_IgnoredValue2]));
		w69.Position = 0;
		w69.Expand = false;
		w69.Fill = false;
		// Container child hbox16.Gtk.Box+BoxChild
		this.lbl_ObejctTeam2 = new global::Gtk.Label();
		this.lbl_ObejctTeam2.Name = "lbl_ObejctTeam2";
		this.lbl_ObejctTeam2.Ypad = 5;
		this.lbl_ObejctTeam2.LabelProp = global::Mono.Unix.Catalog.GetString("Object Team #2");
		this.lbl_ObejctTeam2.UseUnderline = true;
		this.hbox16.Add(this.lbl_ObejctTeam2);
		global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.lbl_ObejctTeam2]));
		w70.Position = 1;
		w70.Expand = false;
		w70.Fill = false;
		// Container child hbox16.Gtk.Box+BoxChild
		this.lbl_MysteryByte2 = new global::Gtk.Label();
		this.lbl_MysteryByte2.Name = "lbl_MysteryByte2";
		this.lbl_MysteryByte2.Ypad = 5;
		this.lbl_MysteryByte2.LabelProp = global::Mono.Unix.Catalog.GetString("Mystery Byte #2");
		this.lbl_MysteryByte2.UseUnderline = true;
		this.hbox16.Add(this.lbl_MysteryByte2);
		global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.lbl_MysteryByte2]));
		w71.Position = 2;
		w71.Expand = false;
		w71.Fill = false;
		// Container child hbox16.Gtk.Box+BoxChild
		this.lbl_MysteryFourBytes2 = new global::Gtk.Label();
		this.lbl_MysteryFourBytes2.Name = "lbl_MysteryFourBytes2";
		this.lbl_MysteryFourBytes2.Ypad = 5;
		this.lbl_MysteryFourBytes2.LabelProp = global::Mono.Unix.Catalog.GetString("Mystery Four Bytes #2");
		this.lbl_MysteryFourBytes2.UseUnderline = true;
		this.hbox16.Add(this.lbl_MysteryFourBytes2);
		global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.lbl_MysteryFourBytes2]));
		w72.Position = 3;
		w72.Expand = false;
		w72.Fill = false;
		this.vbox6.Add(this.hbox16);
		global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox16]));
		w73.Position = 11;
		w73.Expand = false;
		w73.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Homogeneous = true;
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.SpinBtn_IgnoredValue2 = new global::Gtk.SpinButton(0, 65535, 1);
		this.SpinBtn_IgnoredValue2.WidthRequest = 200;
		this.SpinBtn_IgnoredValue2.CanFocus = true;
		this.SpinBtn_IgnoredValue2.Name = "SpinBtn_IgnoredValue2";
		this.SpinBtn_IgnoredValue2.Adjustment.PageIncrement = 1;
		this.SpinBtn_IgnoredValue2.ClimbRate = 1;
		this.SpinBtn_IgnoredValue2.Numeric = true;
		this.SpinBtn_IgnoredValue2.Value = 1;
		this.hbox2.Add(this.SpinBtn_IgnoredValue2);
		global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.SpinBtn_IgnoredValue2]));
		w74.Position = 0;
		w74.Expand = false;
		w74.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.CmbBox_ObjectTeam2 = global::Gtk.ComboBox.NewText();
		this.CmbBox_ObjectTeam2.AppendText(global::Mono.Unix.Catalog.GetString("Base/All"));
		this.CmbBox_ObjectTeam2.AppendText(global::Mono.Unix.Catalog.GetString("Sonic"));
		this.CmbBox_ObjectTeam2.AppendText(global::Mono.Unix.Catalog.GetString("Dark"));
		this.CmbBox_ObjectTeam2.AppendText(global::Mono.Unix.Catalog.GetString("Rose"));
		this.CmbBox_ObjectTeam2.AppendText(global::Mono.Unix.Catalog.GetString("Chaotix"));
		this.CmbBox_ObjectTeam2.AppendText(global::Mono.Unix.Catalog.GetString("Super Hard"));
		this.CmbBox_ObjectTeam2.WidthRequest = 200;
		this.CmbBox_ObjectTeam2.Name = "CmbBox_ObjectTeam2";
		this.CmbBox_ObjectTeam2.Active = 0;
		this.hbox2.Add(this.CmbBox_ObjectTeam2);
		global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.CmbBox_ObjectTeam2]));
		w75.Position = 1;
		w75.Expand = false;
		w75.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.SpinBtn_MysteryByte2 = new global::Gtk.SpinButton(0, 255, 1);
		this.SpinBtn_MysteryByte2.WidthRequest = 200;
		this.SpinBtn_MysteryByte2.CanFocus = true;
		this.SpinBtn_MysteryByte2.Name = "SpinBtn_MysteryByte2";
		this.SpinBtn_MysteryByte2.Adjustment.PageIncrement = 1;
		this.SpinBtn_MysteryByte2.ClimbRate = 1;
		this.SpinBtn_MysteryByte2.Numeric = true;
		this.hbox2.Add(this.SpinBtn_MysteryByte2);
		global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.SpinBtn_MysteryByte2]));
		w76.Position = 2;
		w76.Expand = false;
		w76.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.SpinBtn_MysteryFourBytes2 = new global::Gtk.SpinButton(0, 4294967295, 1);
		this.SpinBtn_MysteryFourBytes2.WidthRequest = 200;
		this.SpinBtn_MysteryFourBytes2.CanFocus = true;
		this.SpinBtn_MysteryFourBytes2.Name = "SpinBtn_MysteryFourBytes2";
		this.SpinBtn_MysteryFourBytes2.Adjustment.PageIncrement = 1;
		this.SpinBtn_MysteryFourBytes2.ClimbRate = 1;
		this.SpinBtn_MysteryFourBytes2.Numeric = true;
		this.hbox2.Add(this.SpinBtn_MysteryFourBytes2);
		global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.SpinBtn_MysteryFourBytes2]));
		w77.Position = 3;
		w77.Expand = false;
		w77.Fill = false;
		this.vbox6.Add(this.hbox2);
		global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox2]));
		w78.Position = 12;
		w78.Expand = false;
		w78.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.lbl_Separator3 = new global::Gtk.Label();
		this.lbl_Separator3.Name = "lbl_Separator3";
		this.lbl_Separator3.LabelProp = global::Mono.Unix.Catalog.GetString("-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
		this.vbox6.Add(this.lbl_Separator3);
		global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.lbl_Separator3]));
		w79.Position = 13;
		w79.Expand = false;
		w79.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.CmbBox_Property = global::Gtk.ComboBox.NewText();
		this.CmbBox_Property.AppendText(global::Mono.Unix.Catalog.GetString("Sample Property <00>"));
		this.CmbBox_Property.WidthRequest = 500;
		this.CmbBox_Property.Name = "CmbBox_Property";
		this.CmbBox_Property.Active = 0;
		this.hbox8.Add(this.CmbBox_Property);
		global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.CmbBox_Property]));
		w80.Position = 0;
		// Container child hbox8.Gtk.Box+BoxChild
		this.lbl_MiscActivator = new global::Gtk.Label();
		this.lbl_MiscActivator.Name = "lbl_MiscActivator";
		this.lbl_MiscActivator.Ypad = 5;
		this.lbl_MiscActivator.LabelProp = global::Mono.Unix.Catalog.GetString("Activator:");
		this.lbl_MiscActivator.UseUnderline = true;
		this.hbox8.Add(this.lbl_MiscActivator);
		global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.lbl_MiscActivator]));
		w81.Position = 1;
		w81.Expand = false;
		w81.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.SpinBtn_MiscActivator = new global::Gtk.SpinButton(0, 65535, 1);
		this.SpinBtn_MiscActivator.WidthRequest = 200;
		this.SpinBtn_MiscActivator.CanFocus = true;
		this.SpinBtn_MiscActivator.Name = "SpinBtn_MiscActivator";
		this.SpinBtn_MiscActivator.Adjustment.PageIncrement = 1;
		this.SpinBtn_MiscActivator.ClimbRate = 1;
		this.SpinBtn_MiscActivator.Numeric = true;
		this.hbox8.Add(this.SpinBtn_MiscActivator);
		global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.SpinBtn_MiscActivator]));
		w82.Position = 2;
		// Container child hbox8.Gtk.Box+BoxChild
		this.lbl_MiscEntryID = new global::Gtk.Label();
		this.lbl_MiscEntryID.Name = "lbl_MiscEntryID";
		this.lbl_MiscEntryID.Ypad = 5;
		this.lbl_MiscEntryID.LabelProp = global::Mono.Unix.Catalog.GetString("Misc Entry ID:");
		this.lbl_MiscEntryID.UseUnderline = true;
		this.hbox8.Add(this.lbl_MiscEntryID);
		global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.lbl_MiscEntryID]));
		w83.Position = 3;
		w83.Expand = false;
		w83.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.SpinBtn_MiscEntryID = new global::Gtk.SpinButton(0, 65535, 1);
		this.SpinBtn_MiscEntryID.WidthRequest = 200;
		this.SpinBtn_MiscEntryID.CanFocus = true;
		this.SpinBtn_MiscEntryID.Name = "SpinBtn_MiscEntryID";
		this.SpinBtn_MiscEntryID.Adjustment.PageIncrement = 1;
		this.SpinBtn_MiscEntryID.ClimbRate = 1;
		this.SpinBtn_MiscEntryID.Numeric = true;
		this.hbox8.Add(this.SpinBtn_MiscEntryID);
		global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.SpinBtn_MiscEntryID]));
		w84.Position = 4;
		this.vbox6.Add(this.hbox8);
		global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox8]));
		w85.Position = 14;
		w85.Expand = false;
		w85.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 0;
		this.notebook1.ShowBorder = false;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox21 = new global::Gtk.HBox();
		this.hbox21.Name = "hbox21";
		this.hbox21.Homogeneous = true;
		this.hbox21.Spacing = 6;
		// Container child hbox21.Gtk.Box+BoxChild
		this.lbl_ObjectProperty1 = new global::Gtk.Label();
		this.lbl_ObjectProperty1.Name = "lbl_ObjectProperty1";
		this.lbl_ObjectProperty1.Ypad = 5;
		this.lbl_ObjectProperty1.LabelProp = global::Mono.Unix.Catalog.GetString("Object Property #1");
		this.lbl_ObjectProperty1.UseUnderline = true;
		this.hbox21.Add(this.lbl_ObjectProperty1);
		global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.lbl_ObjectProperty1]));
		w86.Position = 0;
		w86.Expand = false;
		w86.Fill = false;
		// Container child hbox21.Gtk.Box+BoxChild
		this.lbl_ObjectProperty2 = new global::Gtk.Label();
		this.lbl_ObjectProperty2.Name = "lbl_ObjectProperty2";
		this.lbl_ObjectProperty2.Ypad = 5;
		this.lbl_ObjectProperty2.LabelProp = global::Mono.Unix.Catalog.GetString("Object Property #2");
		this.lbl_ObjectProperty2.UseUnderline = true;
		this.hbox21.Add(this.lbl_ObjectProperty2);
		global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.lbl_ObjectProperty2]));
		w87.Position = 1;
		w87.Expand = false;
		w87.Fill = false;
		// Container child hbox21.Gtk.Box+BoxChild
		this.lbl_ObjectProperty3 = new global::Gtk.Label();
		this.lbl_ObjectProperty3.Name = "lbl_ObjectProperty3";
		this.lbl_ObjectProperty3.Ypad = 5;
		this.lbl_ObjectProperty3.LabelProp = global::Mono.Unix.Catalog.GetString("Object Property #3");
		this.lbl_ObjectProperty3.UseUnderline = true;
		this.hbox21.Add(this.lbl_ObjectProperty3);
		global::Gtk.Box.BoxChild w88 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.lbl_ObjectProperty3]));
		w88.Position = 2;
		w88.Expand = false;
		w88.Fill = false;
		// Container child hbox21.Gtk.Box+BoxChild
		this.lbl_ObjectProperty4 = new global::Gtk.Label();
		this.lbl_ObjectProperty4.Name = "lbl_ObjectProperty4";
		this.lbl_ObjectProperty4.Ypad = 5;
		this.lbl_ObjectProperty4.LabelProp = global::Mono.Unix.Catalog.GetString("Object Property #4");
		this.lbl_ObjectProperty4.UseUnderline = true;
		this.hbox21.Add(this.lbl_ObjectProperty4);
		global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.lbl_ObjectProperty4]));
		w89.Position = 3;
		w89.Expand = false;
		w89.Fill = false;
		this.vbox3.Add(this.hbox21);
		global::Gtk.Box.BoxChild w90 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox21]));
		w90.Position = 0;
		w90.Expand = false;
		w90.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox22 = new global::Gtk.HBox();
		this.hbox22.Name = "hbox22";
		this.hbox22.Homogeneous = true;
		this.hbox22.Spacing = 6;
		// Container child hbox22.Gtk.Box+BoxChild
		this.SpinBtn_ObjectProperty1 = new global::Gtk.SpinButton(-1.175494E+38, 3.402823E+38, 1);
		this.SpinBtn_ObjectProperty1.WidthRequest = 200;
		this.SpinBtn_ObjectProperty1.CanFocus = true;
		this.SpinBtn_ObjectProperty1.Name = "SpinBtn_ObjectProperty1";
		this.SpinBtn_ObjectProperty1.Adjustment.PageIncrement = 1;
		this.SpinBtn_ObjectProperty1.ClimbRate = 1;
		this.SpinBtn_ObjectProperty1.Digits = ((uint)(7));
		this.SpinBtn_ObjectProperty1.Numeric = true;
		this.SpinBtn_ObjectProperty1.Value = -1;
		this.hbox22.Add(this.SpinBtn_ObjectProperty1);
		global::Gtk.Box.BoxChild w91 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.SpinBtn_ObjectProperty1]));
		w91.Position = 0;
		w91.Expand = false;
		w91.Fill = false;
		// Container child hbox22.Gtk.Box+BoxChild
		this.SpinBtn_ObjectProperty2 = new global::Gtk.SpinButton(-1.175494E+38, 3.402823E+38, 1);
		this.SpinBtn_ObjectProperty2.WidthRequest = 200;
		this.SpinBtn_ObjectProperty2.CanFocus = true;
		this.SpinBtn_ObjectProperty2.Name = "SpinBtn_ObjectProperty2";
		this.SpinBtn_ObjectProperty2.Adjustment.PageIncrement = 1;
		this.SpinBtn_ObjectProperty2.ClimbRate = 1;
		this.SpinBtn_ObjectProperty2.Digits = ((uint)(7));
		this.SpinBtn_ObjectProperty2.Numeric = true;
		this.hbox22.Add(this.SpinBtn_ObjectProperty2);
		global::Gtk.Box.BoxChild w92 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.SpinBtn_ObjectProperty2]));
		w92.Position = 1;
		w92.Expand = false;
		w92.Fill = false;
		// Container child hbox22.Gtk.Box+BoxChild
		this.SpinBtn_ObjectProperty3 = new global::Gtk.SpinButton(-1.175494E+38, 3.402823E+38, 1);
		this.SpinBtn_ObjectProperty3.WidthRequest = 200;
		this.SpinBtn_ObjectProperty3.CanFocus = true;
		this.SpinBtn_ObjectProperty3.Name = "SpinBtn_ObjectProperty3";
		this.SpinBtn_ObjectProperty3.Adjustment.PageIncrement = 1;
		this.SpinBtn_ObjectProperty3.ClimbRate = 1;
		this.SpinBtn_ObjectProperty3.Digits = ((uint)(7));
		this.SpinBtn_ObjectProperty3.Numeric = true;
		this.hbox22.Add(this.SpinBtn_ObjectProperty3);
		global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.SpinBtn_ObjectProperty3]));
		w93.Position = 2;
		w93.Expand = false;
		w93.Fill = false;
		// Container child hbox22.Gtk.Box+BoxChild
		this.SpinBtn_ObjectProperty4 = new global::Gtk.SpinButton(-1.175494E+38, 3.402823E+38, 1);
		this.SpinBtn_ObjectProperty4.WidthRequest = 200;
		this.SpinBtn_ObjectProperty4.CanFocus = true;
		this.SpinBtn_ObjectProperty4.Name = "SpinBtn_ObjectProperty4";
		this.SpinBtn_ObjectProperty4.Adjustment.PageIncrement = 1;
		this.SpinBtn_ObjectProperty4.ClimbRate = 1;
		this.SpinBtn_ObjectProperty4.Digits = ((uint)(7));
		this.SpinBtn_ObjectProperty4.Numeric = true;
		this.SpinBtn_ObjectProperty4.Value = -1;
		this.hbox22.Add(this.SpinBtn_ObjectProperty4);
		global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.SpinBtn_ObjectProperty4]));
		w94.Position = 3;
		w94.Expand = false;
		w94.Fill = false;
		this.vbox3.Add(this.hbox22);
		global::Gtk.Box.BoxChild w95 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox22]));
		w95.Position = 1;
		w95.Expand = false;
		w95.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox14 = new global::Gtk.HBox();
		this.hbox14.Name = "hbox14";
		this.hbox14.Homogeneous = true;
		this.hbox14.Spacing = 6;
		// Container child hbox14.Gtk.Box+BoxChild
		this.lbl_ObjectProperty5 = new global::Gtk.Label();
		this.lbl_ObjectProperty5.Name = "lbl_ObjectProperty5";
		this.lbl_ObjectProperty5.Ypad = 5;
		this.lbl_ObjectProperty5.LabelProp = global::Mono.Unix.Catalog.GetString("Object Property #5");
		this.lbl_ObjectProperty5.UseUnderline = true;
		this.hbox14.Add(this.lbl_ObjectProperty5);
		global::Gtk.Box.BoxChild w96 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.lbl_ObjectProperty5]));
		w96.Position = 0;
		w96.Expand = false;
		w96.Fill = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.lbl_ObjectProperty6 = new global::Gtk.Label();
		this.lbl_ObjectProperty6.Name = "lbl_ObjectProperty6";
		this.lbl_ObjectProperty6.Ypad = 5;
		this.lbl_ObjectProperty6.LabelProp = global::Mono.Unix.Catalog.GetString("Object Property #6");
		this.lbl_ObjectProperty6.UseUnderline = true;
		this.hbox14.Add(this.lbl_ObjectProperty6);
		global::Gtk.Box.BoxChild w97 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.lbl_ObjectProperty6]));
		w97.Position = 1;
		w97.Expand = false;
		w97.Fill = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.lbl_ObjectProperty7 = new global::Gtk.Label();
		this.lbl_ObjectProperty7.Name = "lbl_ObjectProperty7";
		this.lbl_ObjectProperty7.Ypad = 5;
		this.lbl_ObjectProperty7.LabelProp = global::Mono.Unix.Catalog.GetString("Object Property #7");
		this.lbl_ObjectProperty7.UseUnderline = true;
		this.hbox14.Add(this.lbl_ObjectProperty7);
		global::Gtk.Box.BoxChild w98 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.lbl_ObjectProperty7]));
		w98.Position = 2;
		w98.Expand = false;
		w98.Fill = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.lbl_ObjectProperty8 = new global::Gtk.Label();
		this.lbl_ObjectProperty8.Name = "lbl_ObjectProperty8";
		this.lbl_ObjectProperty8.Ypad = 5;
		this.lbl_ObjectProperty8.LabelProp = global::Mono.Unix.Catalog.GetString("Object Property #8");
		this.lbl_ObjectProperty8.UseUnderline = true;
		this.hbox14.Add(this.lbl_ObjectProperty8);
		global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.lbl_ObjectProperty8]));
		w99.Position = 3;
		w99.Expand = false;
		w99.Fill = false;
		this.vbox3.Add(this.hbox14);
		global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox14]));
		w100.Position = 2;
		w100.Expand = false;
		w100.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox18 = new global::Gtk.HBox();
		this.hbox18.Name = "hbox18";
		this.hbox18.Homogeneous = true;
		this.hbox18.Spacing = 6;
		// Container child hbox18.Gtk.Box+BoxChild
		this.SpinBtn_ObjectProperty5 = new global::Gtk.SpinButton(-1.175494E+38, 3.402823E+38, 1);
		this.SpinBtn_ObjectProperty5.WidthRequest = 200;
		this.SpinBtn_ObjectProperty5.CanFocus = true;
		this.SpinBtn_ObjectProperty5.Name = "SpinBtn_ObjectProperty5";
		this.SpinBtn_ObjectProperty5.Adjustment.PageIncrement = 1;
		this.SpinBtn_ObjectProperty5.ClimbRate = 1;
		this.SpinBtn_ObjectProperty5.Digits = ((uint)(7));
		this.SpinBtn_ObjectProperty5.Numeric = true;
		this.SpinBtn_ObjectProperty5.Value = -6;
		this.hbox18.Add(this.SpinBtn_ObjectProperty5);
		global::Gtk.Box.BoxChild w101 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.SpinBtn_ObjectProperty5]));
		w101.Position = 0;
		w101.Expand = false;
		w101.Fill = false;
		// Container child hbox18.Gtk.Box+BoxChild
		this.SpinBtn_ObjectProperty6 = new global::Gtk.SpinButton(-1.175494E+38, 3.402823E+38, 1);
		this.SpinBtn_ObjectProperty6.WidthRequest = 200;
		this.SpinBtn_ObjectProperty6.CanFocus = true;
		this.SpinBtn_ObjectProperty6.Name = "SpinBtn_ObjectProperty6";
		this.SpinBtn_ObjectProperty6.Adjustment.PageIncrement = 1;
		this.SpinBtn_ObjectProperty6.ClimbRate = 1;
		this.SpinBtn_ObjectProperty6.Digits = ((uint)(7));
		this.SpinBtn_ObjectProperty6.Numeric = true;
		this.hbox18.Add(this.SpinBtn_ObjectProperty6);
		global::Gtk.Box.BoxChild w102 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.SpinBtn_ObjectProperty6]));
		w102.Position = 1;
		w102.Expand = false;
		w102.Fill = false;
		// Container child hbox18.Gtk.Box+BoxChild
		this.SpinBtn_ObjectProperty7 = new global::Gtk.SpinButton(-1.175494E+38, 3.402823E+38, 1);
		this.SpinBtn_ObjectProperty7.WidthRequest = 200;
		this.SpinBtn_ObjectProperty7.CanFocus = true;
		this.SpinBtn_ObjectProperty7.Name = "SpinBtn_ObjectProperty7";
		this.SpinBtn_ObjectProperty7.Adjustment.PageIncrement = 1;
		this.SpinBtn_ObjectProperty7.ClimbRate = 1;
		this.SpinBtn_ObjectProperty7.Digits = ((uint)(7));
		this.SpinBtn_ObjectProperty7.Numeric = true;
		this.hbox18.Add(this.SpinBtn_ObjectProperty7);
		global::Gtk.Box.BoxChild w103 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.SpinBtn_ObjectProperty7]));
		w103.Position = 2;
		w103.Expand = false;
		w103.Fill = false;
		// Container child hbox18.Gtk.Box+BoxChild
		this.SpinBtn_ObjectProperty8 = new global::Gtk.SpinButton(-1.175494E+38, 3.402823E+38, 1);
		this.SpinBtn_ObjectProperty8.WidthRequest = 200;
		this.SpinBtn_ObjectProperty8.CanFocus = true;
		this.SpinBtn_ObjectProperty8.Name = "SpinBtn_ObjectProperty8";
		this.SpinBtn_ObjectProperty8.Adjustment.PageIncrement = 1;
		this.SpinBtn_ObjectProperty8.ClimbRate = 1;
		this.SpinBtn_ObjectProperty8.Digits = ((uint)(7));
		this.SpinBtn_ObjectProperty8.Numeric = true;
		this.hbox18.Add(this.SpinBtn_ObjectProperty8);
		global::Gtk.Box.BoxChild w104 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.SpinBtn_ObjectProperty8]));
		w104.Position = 3;
		w104.Expand = false;
		w104.Fill = false;
		this.vbox3.Add(this.hbox18);
		global::Gtk.Box.BoxChild w105 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox18]));
		w105.Position = 3;
		w105.Expand = false;
		w105.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox20 = new global::Gtk.HBox();
		this.hbox20.Name = "hbox20";
		this.hbox20.Homogeneous = true;
		this.hbox20.Spacing = 6;
		// Container child hbox20.Gtk.Box+BoxChild
		this.Btn_ViewAsFloats = new global::Gtk.Button();
		this.Btn_ViewAsFloats.Sensitive = false;
		this.Btn_ViewAsFloats.CanFocus = true;
		this.Btn_ViewAsFloats.Name = "Btn_ViewAsFloats";
		this.Btn_ViewAsFloats.UseUnderline = true;
		this.Btn_ViewAsFloats.Label = global::Mono.Unix.Catalog.GetString("Convert Values to Floats");
		this.hbox20.Add(this.Btn_ViewAsFloats);
		global::Gtk.Box.BoxChild w106 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.Btn_ViewAsFloats]));
		w106.Position = 0;
		// Container child hbox20.Gtk.Box+BoxChild
		this.Btn_ViewAsIntegers = new global::Gtk.Button();
		this.Btn_ViewAsIntegers.CanFocus = true;
		this.Btn_ViewAsIntegers.Name = "Btn_ViewAsIntegers";
		this.Btn_ViewAsIntegers.UseUnderline = true;
		this.Btn_ViewAsIntegers.Label = global::Mono.Unix.Catalog.GetString("Convert Values to Integers");
		this.hbox20.Add(this.Btn_ViewAsIntegers);
		global::Gtk.Box.BoxChild w107 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.Btn_ViewAsIntegers]));
		w107.Position = 1;
		this.vbox3.Add(this.hbox20);
		global::Gtk.Box.BoxChild w108 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox20]));
		w108.Position = 4;
		w108.Expand = false;
		w108.Fill = false;
		this.notebook1.Add(this.vbox3);
		// Notebook tab
		this.Page_Floats = new global::Gtk.Label();
		this.Page_Floats.Name = "Page_Floats";
		this.Page_Floats.LabelProp = global::Mono.Unix.Catalog.GetString("Floats/Ints");
		this.notebook1.SetTabLabel(this.vbox3, this.Page_Floats);
		this.Page_Floats.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox19 = new global::Gtk.HBox();
		this.hbox19.Name = "hbox19";
		this.hbox19.Spacing = 6;
		this.vbox2.Add(this.hbox19);
		global::Gtk.Box.BoxChild w110 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox19]));
		w110.Position = 2;
		this.notebook1.Add(this.vbox2);
		global::Gtk.Notebook.NotebookChild w111 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox2]));
		w111.Position = 1;
		// Notebook tab
		this.Page_Bytes = new global::Gtk.Label();
		this.Page_Bytes.Name = "Page_Bytes";
		this.Page_Bytes.LabelProp = global::Mono.Unix.Catalog.GetString("Bytes");
		this.notebook1.SetTabLabel(this.vbox2, this.Page_Bytes);
		this.Page_Bytes.ShowAll();
		this.vbox6.Add(this.notebook1);
		global::Gtk.Box.BoxChild w112 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.notebook1]));
		w112.Position = 15;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox23 = new global::Gtk.HBox();
		this.hbox23.Name = "hbox23";
		this.hbox23.Homogeneous = true;
		this.hbox23.Spacing = 6;
		// Container child hbox23.Gtk.Box+BoxChild
		this.lbl_Statusbar1 = new global::Gtk.Label();
		this.lbl_Statusbar1.Name = "lbl_Statusbar1";
		this.lbl_Statusbar1.LabelProp = global::Mono.Unix.Catalog.GetString("Sonic Location Client | Not Connected");
		this.hbox23.Add(this.lbl_Statusbar1);
		global::Gtk.Box.BoxChild w113 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.lbl_Statusbar1]));
		w113.Position = 0;
		w113.Expand = false;
		w113.Fill = false;
		// Container child hbox23.Gtk.Box+BoxChild
		this.lbl_Statusbar2 = new global::Gtk.Label();
		this.lbl_Statusbar2.Name = "lbl_Statusbar2";
		this.lbl_Statusbar2.LabelProp = global::Mono.Unix.Catalog.GetString("Misc Section Values | Floating Points");
		this.hbox23.Add(this.lbl_Statusbar2);
		global::Gtk.Box.BoxChild w114 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.lbl_Statusbar2]));
		w114.Position = 1;
		w114.Expand = false;
		w114.Fill = false;
		// Container child hbox23.Gtk.Box+BoxChild
		this.lbl_Statusbar3 = new global::Gtk.Label();
		this.lbl_Statusbar3.Name = "lbl_Statusbar3";
		this.lbl_Statusbar3.LabelProp = global::Mono.Unix.Catalog.GetString("Current Stage | (00) Test Level");
		this.hbox23.Add(this.lbl_Statusbar3);
		global::Gtk.Box.BoxChild w115 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.lbl_Statusbar3]));
		w115.Position = 2;
		w115.Expand = false;
		w115.Fill = false;
		this.vbox6.Add(this.hbox23);
		global::Gtk.Box.BoxChild w116 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox23]));
		w116.Position = 16;
		w116.Expand = false;
		w116.Fill = false;
		this.Add(this.vbox6);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 900;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.Btn_OpenFile.Clicked += new global::System.EventHandler(this.OnBtnOpenFileClicked);
		this.Btn_SaveFile.Clicked += new global::System.EventHandler(this.OnBtnSaveFileClicked);
		this.CmbBox_Item.Changed += new global::System.EventHandler(this.OnCmbBoxItemChanged);
		this.btn_ClearAll.Clicked += new global::System.EventHandler(this.OnBtnClearAllClicked);
		this.btn_RemoveObject.Clicked += new global::System.EventHandler(this.OnBtnRemoveObjectClicked);
		this.btn_CloneObject.Clicked += new global::System.EventHandler(this.OnBtnCloneObjectClicked);
		this.CmbBox_SelectByName.Changed += new global::System.EventHandler(this.OnCmbBoxSelectByNameChanged);
		this.CmbBox_SelectByType.Changed += new global::System.EventHandler(this.OnCmbBoxSelectByTypeChanged);
		this.CmbBox_SelectByID.Changed += new global::System.EventHandler(this.OnCmbBoxSelectByIDChanged);
		this.CmbBox_Property.Changed += new global::System.EventHandler(this.OnCmbBoxPropertyChanged);
		this.Btn_ViewAsFloats.Released += new global::System.EventHandler(this.OnBtnViewAsFloatsReleased);
		this.Btn_ViewAsIntegers.Released += new global::System.EventHandler(this.OnBtnViewAsIntegersReleased);
	}
}
