
// This file has been generated by the GUI designer. Do not modify.
namespace SHLayoutEditor
{
	public partial class MainWindowX2
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Label lbl_Windows;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button btn_UseBuiltIn;

		private global::Gtk.Button btn_UseDefault;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SHLayoutEditor.MainWindowX2
			this.WidthRequest = 500;
			this.Name = "SHLayoutEditor.MainWindowX2";
			this.Title = global::Mono.Unix.Catalog.GetString("MainWindowX2");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(15));
			this.AllowShrink = true;
			// Container child SHLayoutEditor.MainWindowX2.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lbl_Windows = new global::Gtk.Label();
			this.lbl_Windows.WidthRequest = 530;
			this.lbl_Windows.Name = "lbl_Windows";
			this.lbl_Windows.LabelProp = global::Mono.Unix.Catalog.GetString("It appears that you are likely running this application inside of Microsoft Windows, in general GTK does not look adequately aesthetically pleasing with the default Windows themes, and as such you have been given a choice of theme, you can either use your own GTK theme, stick to the default Windows theme, or load the bundled theme.");
			this.lbl_Windows.Wrap = true;
			this.lbl_Windows.Justify = ((global::Gtk.Justification)(2));
			this.vbox2.Add(this.lbl_Windows);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.lbl_Windows]));
			w1.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Homogeneous = true;
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btn_UseBuiltIn = new global::Gtk.Button();
			this.btn_UseBuiltIn.CanFocus = true;
			this.btn_UseBuiltIn.Name = "btn_UseBuiltIn";
			this.btn_UseBuiltIn.UseUnderline = true;
			this.btn_UseBuiltIn.Label = global::Mono.Unix.Catalog.GetString("Use Built-In GTK Theme");
			this.hbox1.Add(this.btn_UseBuiltIn);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btn_UseBuiltIn]));
			w2.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btn_UseDefault = new global::Gtk.Button();
			this.btn_UseDefault.CanFocus = true;
			this.btn_UseDefault.Name = "btn_UseDefault";
			this.btn_UseDefault.UseUnderline = true;
			this.btn_UseDefault.Label = global::Mono.Unix.Catalog.GetString("Keep Default Appearance");
			this.hbox1.Add(this.btn_UseDefault);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btn_UseDefault]));
			w3.Position = 1;
			this.vbox2.Add(this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 555;
			this.DefaultHeight = 311;
			this.Show();
			this.btn_UseBuiltIn.Clicked += new global::System.EventHandler(this.OnBtnUseBuiltInClicked);
			this.btn_UseDefault.Clicked += new global::System.EventHandler(this.OnBtnUseGTKClicked);
		}
	}
}
