mkdir "Stage 01 - Seaside Hill"
mkdir "Stage 02 - Ocean Palace"
mkdir "Stage 03 - Grand Metropolis"
mkdir "Stage 04 - Power Plant"
mkdir "Stage 11 - Hang Castle"
mkdir "Stage 12 - Mystic Mansion"
mkdir "Stage 13 - Egg Fleet"
mkdir "Stage 14 - Final Fortress"
mkdir "Stage 20 - Egg Hawk"
mkdir "Stage 21 - Team Battle 1"
mkdir "Stage 22 - Robot Carnival"
mkdir "Stage 23 - Egg Albatross"
mkdir "Stage 25 - Final Fortress"
mkdir "Stage 27 - Metal Madness"
mkdir "Stage 28 - Metal Overlord"
mkdir "Stage 29 - Sea Gate"
mkdir "Stage 31 - Seaside Course"
mkdir "Stage 32 - City Course"
mkdir "Stage 33 - Casino Course"
mkdir "Stage 60 - Seaside Hill 2P"
mkdir "Stage 61 - Grand Metropolis 2P"
mkdir "Stage 63 - City Top 2P"
mkdir "Stage 65 - Turtle Shell 2P"
mkdir "Stage 66 - Egg Treat 2P"
mkdir "Stage 68 - Hot Elevator 2P"
mkdir "Stage 69 - Road Rock 2P"
mkdir "Stage 71 - Terror Hall 2P"
mkdir "Stage 74 - Egg Fleet 2P"

mkdir "Stage 00 - Test Level"
mkdir "Stage 05 - Casino Park"
mkdir "Stage 06 - BINGO Highway"
mkdir "Stage 07 - Rail Canyon"
mkdir "Stage 08 - Bullet Station"
mkdir "Stage 09 - Frog Forest"
mkdir "Stage 10 - Lost Jungle"
mkdir "Stage 24 - Team Battle 2"
mkdir "Stage 26 - Egg Emperor"
mkdir "Stage 40 - Bonus Stage 2"
mkdir "Stage 41 - Bonus Stage 1"
mkdir "Stage 42 - Bonus Stage 3"
mkdir "Stage 43 - Bonus Stage 4"
mkdir "Stage 44 - Bonus Stage 5"
mkdir "Stage 45 - Bonus Stage 6"
mkdir "Stage 46 - Bonus Stage 7"
mkdir "Stage 50 - Team Chaotix Rail Canyon"
mkdir "Stage 62 - BINGO Highway 2P"
mkdir "Stage 64 - Casino Ring 2P"
mkdir "Stage 67 - Pinball Match 2P"
mkdir "Stage 70 - Mad Express 2P"
mkdir "Stage 72 - Rail Canyon 2P"
mkdir "Stage 73 - Frog Forest 2P"
mkdir "Stage 80 - Emerald Challenge 2"
mkdir "Stage 81 - Emerald Challenge 1"
mkdir "Stage 82 - Emerald Challenge 3"
mkdir "Stage 83 - Emerald Challenge 4"
mkdir "Stage 84 - Emerald Challenge 5"
mkdir "Stage 85 - Emerald Challenge 6"
mkdir "Stage 86 - Emerald Challenge 7"
mkdir "Stage 87 - Special Stage 1 2P"
mkdir "Stage 88 - Special Stage 2 2P"
mkdir "Stage 89 - Special Stage 3 2P"

mkdir "Stage 15 - Unused"
mkdir "Stage 16 - Unused"
mkdir "Stage 17 - Unused"
mkdir "Stage 18 - Unused"
mkdir "Stage 19 - Unused"
mkdir "Stage 30 - Unused"
mkdir "Stage 34 - Unused"
mkdir "Stage 35 - Unused"
mkdir "Stage 36 - Unused"
mkdir "Stage 37 - Unused"
mkdir "Stage 38 - Unused"
mkdir "Stage 39 - Unused"
mkdir "Stage 47 - Unused"
mkdir "Stage 48 - Unused"
mkdir "Stage 49 - Unused"
mkdir "Stage 51 - Unused"
mkdir "Stage 52 - Unused"
mkdir "Stage 53 - Unused"
mkdir "Stage 54 - Unused"
mkdir "Stage 55 - Unused"
mkdir "Stage 56 - Unused"
mkdir "Stage 57 - Unused"
mkdir "Stage 58 - Unused"
mkdir "Stage 59 - Unused"
mkdir "Stage 75 - Unused"
mkdir "Stage 76 - Unused"
mkdir "Stage 77 - Unused"
mkdir "Stage 78 - Unused"
mkdir "Stage 79 - Unused"
mkdir "Stage 90 - Unused"
mkdir "Stage 91 - Unused"
mkdir "Stage 92 - Unused"
mkdir "Stage 93 - Unused"
mkdir "Stage 94 - Unused"
mkdir "Stage 95 - Unused"
mkdir "Stage 96 - Unused"
mkdir "Stage 97 - Unused"
mkdir "Stage 98 - Unused"
mkdir "Stage 99 - Unused"