ren stg01title_disp "Stage 01 - Seaside Hill"
ren stg01title_dispEX "Extra Mission"
ren stg01title_dispSH "Super Hard Mode"
move "Extra Mission" "Stage 01 - Seaside Hill\"
move "Super Hard Mode" "Stage 01 - Seaside Hill\"

ren stg02title_disp "Stage 02 - Ocean Palace"
ren stg02title_dispEX "Extra Mission"
ren stg02title_dispSH "Super Hard Mode"
move "Extra Mission" "Stage 02 - Ocean Palace\"
move "Super Hard Mode" "Stage 02 - Ocean Palace\"

ren stg03title_disp "Stage 03 - Grand Metropolis"
ren stg03title_dispEX "Extra Mission"
ren stg03title_dispSH "Super Hard Mode"
move "Extra Mission" "Stage 03 - Grand Metropolis\"
move "Super Hard Mode" "Stage 03 - Grand Metropolis\"

ren stg04title_disp "Stage 04 - Power Plant"
ren stg04title_dispEX "Extra Mission"
ren stg04title_dispSH "Super Hard Mode"
move "Extra Mission" "Stage 04 - Power Plant\"
move "Super Hard Mode" "Stage 04 - Power Plant\"

ren stg05title_disp "Stage 05 - Casino Park"
ren stg05title_dispEX "Extra Mission"
ren stg05title_dispSH "Super Hard Mode"
move "Extra Mission" "Stage 05 - Casino Park\"
move "Super Hard Mode" "Stage 05 - Casino Park\"

ren stg06title_disp "Stage 06 - BINGO Highway"
ren stg06title_dispEX "Extra Mission"
ren stg06title_dispSH "Super Hard Mode"
move "Extra Mission" "Stage 06 - BINGO Highway\"
move "Super Hard Mode" "Stage 06 - BINGO Highway\"

ren stg07title_disp "Stage 07 - Rail Canyon"
ren stg07title_dispEX "Extra Mission"
ren stg07title_dispSH "Super Hard Mode"
move "Extra Mission" "Stage 07 - Rail Canyon\"
move "Super Hard Mode" "Stage 07 - Rail Canyon\"

ren stg08title_disp "Stage 08 - Bullet Station"
ren stg08title_dispEX "Extra Mission"
ren stg08title_dispSH "Super Hard Mode"
move "Extra Mission" "Stage 08 - Bullet Station\"
move "Super Hard Mode" "Stage 08 - Bullet Station\"

ren stg09title_disp "Stage 09 - Frog Forest"
ren stg09title_dispEX "Extra Mission"
ren stg09title_dispSH "Super Hard Mode"
move "Extra Mission" "Stage 09 - Frog Forest\"
move "Super Hard Mode" "Stage 09 - Frog Forest\"

ren stg10title_disp "Stage 10 - Lost Jungle"
ren stg10title_dispEX "Extra Mission"
ren stg10title_dispSH "Super Hard Mode"
move "Extra Mission" "Stage 10 - Lost Jungle\"
move "Super Hard Mode" "Stage 10 - Lost Jungle\"

ren stg11title_disp "Stage 11 - Hang Castle"
ren stg11title_dispEX "Extra Mission"
ren stg11title_dispSH "Super Hard Mode"
move "Extra Mission" "Stage 11 - Hang Castle\"
move "Super Hard Mode" "Stage 11 - Hang Castle\"

ren stg12title_disp "Stage 12 - Mystic Mansion"
ren stg12title_dispEX "Extra Mission"
ren stg12title_dispSH "Super Hard Mode"
move "Extra Mission" "Stage 12 - Mystic Mansion\"
move "Super Hard Mode" "Stage 12 - Mystic Mansion\"

ren stg13title_disp "Stage 13 - Egg Fleet"
ren stg13title_dispEX "Extra Mission"
ren stg13title_dispSH "Super Hard Mode"
move "Extra Mission" "Stage 13 - Egg Fleet\"
move "Super Hard Mode" "Stage 13 - Egg Fleet\"

ren stg14title_disp "Stage 14 - Final Fortress"
ren stg14title_dispEX "Extra Mission"
ren stg14title_dispSH "Super Hard Mode"
move "Extra Mission" "Stage 14 - Final Fortress\"
move "Super Hard Mode" "Stage 14 - Final Fortress\"

ren stg20title_disp "Stage 20 - Egg Hawk"
ren stg20title_dispE "English"
move "English" "Stage 20 - Egg Hawk\"

ren stg22title_disp "Stage 22 - Robot Carnival"
ren stg22title_dispE "English"
move "English" "Stage 22 - Robot Carnival\"

ren stg23title_disp "Stage 23 - Egg Albatross"
ren stg23title_dispE "English"
move "English" "Stage 23 - Egg Albatross\"

ren stg25title_disp "Stage 25 - Robot Storm"
ren stg25title_dispE "English"
move "English" "Stage 25 - Robot Storm\"

ren stg26title_disp "Stage 26 - Egg Emperor"
ren stg26title_dispE "English"
move "English" "Stage 26- Egg Emperor\"

ren stg27title_disp "Stage 27 - Metal Madness"
ren stg27title_dispE "English"
move "English" "Stage 27 - Metal Madness\"

ren stg28title_disp "Stage 28 - Metal Overlord"
ren stg28title_dispE "English"
move "English" "Stage 28 - Metal Overlord\"

ren stg31title_disp "Stage 31 - Seaside Course"
ren stg32title_disp "Stage 32 - City Course"
ren stg33title_disp "Stage 33 - Casino Course"

ren stg40title_disp "Stage 40 - Special Stage Act 1"
ren stg40title_dispE "English"
ren stg40title_dispF "French"
ren stg40title_dispG "German"
ren stg40title_dispI "Italian"
ren stg40title_dispS "Spanish"
move "English" "Stage 40 - Special Stage Act 1\"
move "French" "Stage 40 - Special Stage Act 1\"
move "German" "Stage 40 - Special Stage Act 1\"
move "Italian" "Stage 40 - Special Stage Act 1\"
move "Spanish" "Stage 40 - Special Stage Act 1\"

ren stg41title_disp "Stage 41 - Special Stage Act 2"
ren stg41title_dispE "English"
ren stg41title_dispF "French"
ren stg41title_dispG "German"
ren stg41title_dispI "Italian"
ren stg41title_dispS "Spanish"
move "English" "Stage 41 - Special Stage Act 2\"
move "French" "Stage 41 - Special Stage Act 2\"
move "German" "Stage 41 - Special Stage Act 2\"
move "Italian" "Stage 41 - Special Stage Act 2\"
move "Spanish" "Stage 41 - Special Stage Act 2\"

ren stg42title_disp "Stage 42 - Special Stage Act 3"
ren stg42title_dispE "English"
ren stg42title_dispF "French"
ren stg42title_dispG "German"
ren stg42title_dispI "Italian"
ren stg42title_dispS "Spanish"
move "English" "Stage 42 - Special Stage Act 3\"
move "French" "Stage 42 - Special Stage Act 3\"
move "German" "Stage 42 - Special Stage Act 3\"
move "Italian" "Stage 42 - Special Stage Act 3\"
move "Spanish" "Stage 42 - Special Stage Act 3\"

ren stg43title_disp "Stage 43 - Special Stage Act 4"
ren stg43title_dispE "English"
ren stg43title_dispF "French"
ren stg43title_dispG "German"
ren stg43title_dispI "Italian"
ren stg43title_dispS "Spanish"
move "English" "Stage 43 - Special Stage Act 4\"
move "French" "Stage 43 - Special Stage Act 4\"
move "German" "Stage 43 - Special Stage Act 4\"
move "Italian" "Stage 43 - Special Stage Act 4\"
move "Spanish" "Stage 43 - Special Stage Act 4\"

ren stg44title_disp "Stage 44 - Special Stage Act 5"
ren stg44title_dispE "English"
ren stg44title_dispF "French"
ren stg44title_dispG "German"
ren stg44title_dispI "Italian"
ren stg44title_dispS "Spanish"
move "English" "Stage 44 - Special Stage Act 5\"
move "French" "Stage 44 - Special Stage Act 5\"
move "German" "Stage 44 - Special Stage Act 5\"
move "Italian" "Stage 44 - Special Stage Act 5\"
move "Spanish" "Stage 44 - Special Stage Act 5\"

ren stg45title_disp "Stage 45 - Special Stage Act 6"
ren stg45title_dispE "English"
ren stg45title_dispF "French"
ren stg45title_dispG "German"
ren stg45title_dispI "Italian"
ren stg45title_dispS "Spanish"
move "English" "Stage 45 - Special Stage Act 6\"
move "French" "Stage 45 - Special Stage Act 6\"
move "German" "Stage 45 - Special Stage Act 6\"
move "Italian" "Stage 45 - Special Stage Act 6\"
move "Spanish" "Stage 45 - Special Stage Act 6\"

ren stg46title_disp "Stage 46 - Special Stage Act 7"
ren stg46title_dispE "English"
ren stg46title_dispF "French"
ren stg46title_dispG "German"
ren stg46title_dispI "Italian"
ren stg46title_dispS "Spanish"
move "English" "Stage 46 - Special Stage Act 7\"
move "French" "Stage 46 - Special Stage Act 7\"
move "German" "Stage 46 - Special Stage Act 7\"
move "Italian" "Stage 46 - Special Stage Act 7\"
move "Spanish" "Stage 46 - Special Stage Act 7\"

ren stg60title_disp "Stage 60 - Seaside Hill 2P"
ren stg61title_disp "Stage 61 - Grand Metropolis 2P"
ren stg62title_disp "Stage 62 - BINGO Highway 2P"
ren stg63title_disp "Stage 63 - City Top 2P"
ren stg64title_disp "Stage 64 - Casino Ring 2P"
ren stg65title_disp "Stage 65 - Turtle Shell 2P"
ren stg66title_disp "Stage 66 - Egg Treat 2P"
ren stg67title_disp "Stage 67 - Pinball Match 2P"
ren stg68title_disp "Stage 68 - Hot Elevator 2P"
ren stg69title_disp "Stage 69 - Road Rock 2P"
ren stg70title_disp "Stage 70 - Mad Express 2P"
ren stg71title_disp "Stage 71 - Terror Hall 2P"
ren stg72title_disp "Stage 72 - Rail Canyon 2P"
ren stg73title_disp "Stage 73 - Frog Forest 2P"
ren stg74title_disp "Stage 74 - Egg Fleet 2P"

ren stg87title_disp "Stage 87 - Special Stage 1 2P"
ren stg87title_dispE "English"
ren stg87title_dispF "French"
ren stg87title_dispG "German"
ren stg87title_dispI "Italian"
ren stg87title_dispS "Spanish"
move "English" "Stage 87 - Special Stage 1 2P\"
move "French" "Stage 87 - Special Stage 1 2P\"
move "German" "Stage 87 - Special Stage 1 2P\"
move "Italian" "Stage 87 - Special Stage 1 2P\"
move "Spanish" "Stage 87 - Special Stage 1 2P\"

ren stg88title_disp "Stage 88 - Special Stage 2 2P"
ren stg88title_dispE "English"
ren stg88title_dispF "French"
ren stg88title_dispG "German"
ren stg88title_dispI "Italian"
ren stg88title_dispS "Spanish"
move "English" "Stage 88 - Special Stage 2 2P\"
move "French" "Stage 88 - Special Stage 2 2P\"
move "German" "Stage 88 - Special Stage 2 2P\"
move "Italian" "Stage 88 - Special Stage 2 2P\"
move "Spanish" "Stage 88 - Special Stage 2 2P\"

ren stg89title_disp "Stage 89 - Special Stage 3 2P"
ren stg89title_dispE "English"
ren stg89title_dispF "French"
ren stg89title_dispG "German"
ren stg89title_dispI "Italian"
ren stg89title_dispS "Spanish"
move "English" "Stage 89 - Special Stage 3 2P\"
move "French" "Stage 89 - Special Stage 3 2P\"
move "German" "Stage 89 - Special Stage 3 2P\"
move "Italian" "Stage 89 - Special Stage 3 2P\"
move "Spanish" "Stage 89 - Special Stage 3 2P\"

ren stgCHAOTIXtitle_disp "Stage XX - Team Chaotix"
ren stgCHAOTIXtitle_dispE "English"
move "English" "Stage XX - Team Chaotix\"

ren stgDARKtitle_disp "Stage XX - Team Dark"
ren stgDARKtitle_dispE "English"
move "English" "Stage XX - Team Dark\"

ren stgROSEtitle_disp "Stage XX - Team Rose"
ren stgROSEtitle_dispE "English"
move "English" "Stage XX - Team Rose\"

ren stgSONICtitle_disp "Stage XX - Team Sonic"
ren stgSONICtitle_dispE "English"
move "English" "Stage XX - Team Sonic\"

ren stgtitle_dispE "Generic Stage - English"
ren stgtitle_dispEEX "Extra Mission"
ren stgtitle_dispESH "Super Hard Mode"
move "Extra Mission" "Generic Stage - English\"
move "Super Hard Mode" "Generic Stage - English\"

ren stgtitle_dispF "Generic Stage - French"
ren stgtitle_dispFEX "Extra Mission"
ren stgtitle_dispFSH "Super Hard Mode"
move "Extra Mission" "Generic Stage - French\"
move "Super Hard Mode" "Generic Stage - French\"

ren stgtitle_dispG "Generic Stage - German"
ren stgtitle_dispGEX "Extra Mission"
ren stgtitle_dispGSH "Super Hard Mode"
move "Extra Mission" "Generic Stage - German\"
move "Super Hard Mode" "Generic Stage - German\"

ren stgtitle_dispI "Generic Stage - Italian"
ren stgtitle_dispIEX "Extra Mission"
ren stgtitle_dispISH "Super Hard Mode"
move "Extra Mission" "Generic Stage - Italian\"
move "Super Hard Mode" "Generic Stage - Italian\"

ren stgtitle_dispS "Generic Stage - Spanish"
ren stgtitle_dispSEX "Extra Mission"
ren stgtitle_dispSSH "Super Hard Mode"
move "Extra Mission" "Generic Stage - Spanish\"
move "Super Hard Mode" "Generic Stage - Spanish\"
