ren s01obj "Stage 01 - Seaside Hill"
ren s02obj "Stage 02 - Ocean Palace"
ren s03obj "Stage 03 - Grand Metropolis"
ren s04obj "Stage 04 - Power Plant"
ren s11obj "Stage 11 - Hang Castle"
ren s12obj "Stage 12 - Mystic Mansion"
ren s13obj "Stage 13 - Egg Fleet"
ren s14obj "Stage 14 - Final Fortress"
ren s20obj "Stage 20 - Egg Hawk"
ren s21obj "Stage 21 - Team Battle 1"
ren s22obj "Stage 22 - Robot Carnival"
ren s23obj "Stage 23 - Egg Albatross"
ren s25obj "Stage 25 - Final Fortress"
ren s27obj "Stage 27 - Metal Madness"
ren s28obj "Stage 28 - Metal Overlord"
ren s29obj "Stage 29 - Sea Gate"
ren s31obj "Stage 31 - Seaside Course"
ren s32obj "Stage 32 - City Course"
ren s33obj "Stage 33 - Casino Course"
ren s60obj "Stage 60 - Seaside Hill 2P"
ren s61obj "Stage 61 - Grand Metropolis 2P"
ren s63obj "Stage 63 - City Top 2P"
ren s65obj "Stage 65 - Turtle Shell 2P"
ren s66obj "Stage 66 - Egg Treat 2P"
ren s68obj "Stage 68 - Hot Elevator 2P"
ren s69obj "Stage 69 - Road Rock 2P"
ren s71obj "Stage 71 - Terror Hall 2P"
ren s74obj "Stage 74 - Egg Fleet 2P"
ren stg00obj "Stage 00 - Test Level"
ren stg05obj "Stage 05 - Casino Park"
ren stg06obj "Stage 06 - BINGO Highway"
ren stg07obj "Stage 07 - Rail Canyon"
ren stg08obj "Stage 08 - Bullet Station"
ren stg09obj "Stage 09 - Frog Forest"
ren stg10obj "Stage 10 - Lost Jungle"
ren stg24obj "Stage 24 - Team Battle 2"
ren stg26obj "Stage 26 - Egg Emperor"
ren stg40obj "Stage 40 - Bonus Stage 2"
ren stg41obj "Stage 41 - Bonus Stage 1"
ren stg42obj "Stage 42 - Bonus Stage 3"
ren stg43obj "Stage 43 - Bonus Stage 4"
ren stg44obj "Stage 44 - Bonus Stage 5"
ren stg45obj "Stage 45 - Bonus Stage 6"
ren stg46obj "Stage 46 - Bonus Stage 7"
ren stg50obj "Stage 50 - Team Chaotix Rail Canyon"
ren stg62obj "Stage 62 - BINGO Highway 2P"
ren stg64obj "Stage 64 - Casino Ring 2P"
ren stg67obj "Stage 67 - Pinball Match 2P"
ren stg70obj "Stage 70 - Mad Express 2P"
ren stg72obj "Stage 72 - Rail Canyon 2P"
ren stg73obj "Stage 73 - Frog Forest 2P"
ren stg80obj "Stage 80 - Emerald Challenge 2"
ren stg81obj "Stage 81 - Emerald Challenge 1"
ren stg82obj "Stage 82 - Emerald Challenge 3"
ren stg83obj "Stage 83 - Emerald Challenge 4"
ren stg84obj "Stage 84 - Emerald Challenge 5"
ren stg85obj "Stage 85 - Emerald Challenge 6"
ren stg86obj "Stage 86 - Emerald Challenge 7"
ren stg87obj "Stage 87 - Special Stage 1 2P"
ren stg88obj "Stage 88 - Special Stage 2 2P"
ren stg89obj "Stage 89 - Special Stage 3 2P"
ren s04_flyer "Stage 04 - Power Plant - Falco Enemy Model & Paths"
ren s13_flyer "Stage 13 - Egg Fleet - Falco Enemy Model & Paths"
ren s22_flyer "Stage 22 - Robot Carnival - Falco Enemy Model & Paths"
ren s23_flyer "Stage 23 - Egg Albatross - Falco Enemy Model & Paths"
ren s25_flyer "Stage 25 - Robot Storm - Falco Enemy Model & Paths"
ren stg00_flyer "Stage 00 - Test Level - Falco Enemy Model & Paths"
ren stg09_flyer "Stage 09 - Frog Forest - Falco Enemy Model & Paths"
ren stg10_flyer "Stage 10 - Lost Jungle - Falco Enemy Model & Paths"
ren stg26_flyer "Stage 26 - Egg Emperor - Falco Enemy Model & Paths"
ren stg80BJ "'Stage 80' - Emerald Challenge X - Common Object Models"
ren stg40MRG "Stage 40 - Bonus Stage 2 - Geometry and Environment Models"
ren stg41MRG "Stage 41 - Bonus Stage 1 - Geometry and Environment Models"
ren stg42MRG "Stage 42 - Bonus Stage 3 - Geometry and Environment Models"
ren stg43MRG "Stage 43 - Bonus Stage 4 - Geometry and Environment Models"
ren stg44MRG "Stage 44 - Bonus Stage 5 - Geometry and Environment Models"
ren stg45MRG "Stage 45 - Bonus Stage 6 - Geometry and Environment Models"
ren stg46MRG "Stage 46 - Bonus Stage 7 - Geometry and Environment Models"
ren stg80MRG "Stage 80 - Emerald Challenge 2 - Geometry and Environment Models"
ren stg81MRG "Stage 81 - Emerald Challenge 1 - Geometry and Environment Models"
ren stg82MRG "Stage 82 - Emerald Challenge 3 - Geometry and Environment Models"
ren stg83MRG "Stage 83 - Emerald Challenge 4 - Geometry and Environment Models"
ren stg84MRG "Stage 84 - Emerald Challenge 5 - Geometry and Environment Models"
ren stg85MRG "Stage 85 - Emerald Challenge 6 - Geometry and Environment Models"
ren stg86MRG "Stage 86 - Emerald Challenge 7 - Geometry and Environment Models"
ren stg87MRG "Stage 87 - Special Stage 1 2P - Geometry and Environment Models"
ren stg88MRG "Stage 88 - Special Stage 2 2P - Geometry and Environment Models"
ren stg89MRG "Stage 89 - Special Stage 3 2P - Geometry and Environment Models"