mkdir "Amy"
mkdir "CharmyBee"
mkdir "BigTheCat"
mkdir "Cream"
mkdir "Espio"
mkdir "Knuckles"
mkdir "Omega"
mkdir "Rouge"
mkdir "Shadow"
mkdir "Sonic"
mkdir "Tails"
mkdir "Vector"
mkdir "AllPlayers"
mkdir "Unused~Unidentified"
move /Y adv_pl_amy.one "Amy\"
move /Y adv_pl_bee.one "CharmyBee\"
move /Y adv_pl_big.one "BigTheCat\"
move /Y adv_pl_cream.one "Cream\"
move /Y adv_pl_espio.one "Espio\"
move /Y adv_pl_knuckles.one "Knuckles\"
move /Y adv_pl_omega.one "Omega\"
move /Y adv_pl_rouge.one "Rouge\"
move /Y adv_pl_shadow.one "Shadow\"
move /Y adv_pl_sonic.one "Sonic\"
move /Y adv_pl_tails.one "Tails\"
move /Y adv_pl_vector.one "Vector\"
move /Y adv_player.one "AllPlayers\"
for %%f in (adv_pl*.one) do (move /Y %%f "Unused~Unidentified\")