mkdir "MainMenuBackgroundAssets"
mkdir "MainMenuOmochao"
mkdir "MainMenuOmochaoHelpIcon"
mkdir "AutosaveMenu"
mkdir "CreditsScreenLogos"
mkdir "MainMenuWindowTextures"
mkdir "EmblemCountSpinningEmblem"

move /Y adv_bg.one "MainMenuBackgroundAssets\"
move /Y adv_chao.one "MainMenuOmochao\"
move /Y adv_help.one "MainMenuOmochaoHelpIcon\"
move /Y adv_save.one "AutosaveMenu\"
move /Y adv_staffroll.one "CreditsScreenLogos\"
move /Y adv_window.one "MainMenuWindowTextures\"
move /Y as_emblem.one "EmblemCountSpinningEmblem\"